---
# Manage all the Gitlab CI variables for a given project

#
# `project_gitlab_ci_variables` is a dictionnary of the form
#
#    name: <project path>
#    kind: project
#    variables:
#      - key: VARIABLE
#        value: xxxx
#        ...
#

- set_fact:
    kind_gitlab_ci: "{{ project_gitlab_ci_variables.kind | default('project') }}"

- set_fact:
    project_gitlab_ci: "{{ project_gitlab_ci_variables.name | replace('/', '%2F') }}"

- include: "ci_variable.yaml"
  with_items: "{{ project_gitlab_ci_variables.variables }}"
  loop_control:
    loop_var: gitlab_ci_variable

- include: "unknown_ci_variables.yaml"
  when: gitlab_ci_check_unknown
